In [77]:
import pandas as pd
import pathlib
from nba_api.stats.endpoints import leaguegamefinder

In [78]:
games = leaguegamefinder.LeagueGameFinder(
    season_nullable="2024-25",
    season_type_nullable="Regular Season"
)
df = games.league_game_finder_results.get_data_frame()

In [79]:
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22024,1610612738,BOS,Boston Celtics,0022401187,2025-04-13,BOS vs. CHA,W,241,93,...,0.692,15,34,49,22,12,6,13,14,7.0
1,22024,1610612747,LAL,Los Angeles Lakers,0022401199,2025-04-13,LAL @ POR,L,239,81,...,0.714,13,29,42,21,9,11,20,21,-28.0
2,22024,1610612759,SAS,San Antonio Spurs,0022401197,2025-04-13,SAS vs. TOR,W,240,125,...,0.875,9,41,50,22,11,2,12,13,7.0
3,22024,1610612754,IND,Indiana Pacers,0022401189,2025-04-13,IND @ CLE,W,289,126,...,0.909,14,47,61,27,15,10,13,20,8.0
4,22024,1610612760,OKC,Oklahoma City Thunder,0022401196,2025-04-13,OKC @ NOP,W,241,115,...,0.889,17,37,54,16,8,4,10,25,15.0

In [80]:
df.shape

(2460, 28)

In [81]:
df.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='str')

In [88]:
df.describe()

,TEAM_ID,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
count,2.460000e+03,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,...,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.00000
mean,1.610613e+09,241.369919,113.825203,41.693496,89.238618,0.468222,13.538211,37.582927,0.359893,16.900000,...,0.779811,11.119106,32.993089,44.112195,26.549593,8.204878,4.876016,13.503252,18.595935,0.00000
std,8.657201e+00,5.982466,12.711950,5.266732,7.290212,0.054332,3.954880,7.033588,0.080627,5.720457,...,0.100398,3.952653,5.423087,6.725460,5.288003,3.089734,2.457047,3.976598,4.204045,15.96616
min,1.610613e+09,237.000000,67.000000,22.000000,67.000000,0.293000,3.000000,12.000000,0.095000,3.000000,...,0.333000,1.000000,16.000000,23.000000,9.000000,1.000000,0.000000,3.000000,5.000000,-59.00000
25%,1.610613e+09,239.000000,105.000000,38.000000,84.000000,0.430000,11.000000,33.000000,0.306000,13.000000,...,0.714000,8.000000,29.000000,39.000000,23.000000,6.000000,3.000000,11.000000,16.000000,-10.00000
50%,1.610613e+09,240.000000,114.000000,42.000000,89.000000,0.468000,13.000000,37.000000,0.358000,16.000000,...,0.786000,11.000000,33.000000,44.000000,26.000000,8.000000,5.000000,13.000000,18.000000,0.00000
75%,1.610613e+09,241.000000,122.000000,45.000000,94.000000,0.506000,16.000000,42.000000,0.413000,21.000000,...,0.846000,14.000000,37.000000,48.000000,30.000000,10.000000,6.000000,16.000000,21.000000,10.00000
max,1.610613e+09,292.000000,162.000000,60.000000,119.000000,0.689000,29.000000,63.000000,0.680000,43.000000,...,1.000000,28.000000,52.000000,73.000000,48.000000,22.000000,18.000000,31.000000,35.000000,59.00000

In [82]:
pathlib.Path("data").mkdir(exist_ok=True)
df.to_csv("data/games.csv", index=False)

In [83]:
# Count the number of @ games
n_at_games = len(df[df["MATCHUP"].str.contains("@")])
# Count the number of vs. games
n_vs_games = len(df[df["MATCHUP"].str.contains("vs.", regex=False)])

print(f"Number of @ games: {n_at_games}")
print(f"Number of vs. games: {n_vs_games}")

Number of @ games: 1235
Number of vs. games: 1225

In [84]:
# Create column that returns True if the team is the home team
df["is_home"] = df["MATCHUP"].str.contains("vs.", regex=False)

# Group by GAME_ID and sum "is_home"; filter for rows where sum is 0
home_counts = df.groupby("GAME_ID")["is_home"].sum()

df[df["GAME_ID"].isin(home_counts[home_counts==0].index)]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,is_home
1137,22024,1610612759,SAS,San Antonio Spurs,0022400633,2025-01-25,IND @ SAS,L,241,98,...,15,29,44,22,9,5,22,17,-38.0,False
1142,22024,1610612754,IND,Indiana Pacers,0022400633,2025-01-25,IND @ SAS,W,240,136,...,16,34,50,32,14,9,10,20,38.0,False
1155,22024,1610612754,IND,Indiana Pacers,0022400621,2025-01-23,SAS @ IND,L,242,110,...,9,22,31,31,10,2,11,9,-30.0,False
1157,22024,1610612759,SAS,San Antonio Spurs,0022400621,2025-01-23,SAS @ IND,W,241,140,...,15,42,57,43,10,10,19,13,30.0,False
1708,22024,1610612749,MIL,Milwaukee Bucks,0022401229,2024-12-14,ATL @ MIL,W,239,110,...,6,41,47,28,8,8,12,27,8.0,False
1709,22024,1610612745,HOU,Houston Rockets,0022401230,2024-12-14,HOU @ OKC,L,240,96,...,19,30,49,17,7,3,16,25,-15.0,False
1710,22024,1610612737,ATL,Atlanta Hawks,0022401229,2024-12-14,ATL @ MIL,L,241,102,...,7,37,44,23,3,6,13,20,-8.0,False
1711,22024,1610612760,OKC,Oklahoma City Thunder,0022401230,2024-12-14,HOU @ OKC,W,241,111,...,4,39,43,19,12,4,12,24,15.0,False
2283,22024,1610612764,WAS,Washington Wizards,0022400147,2024-11-02,MIA @ WAS,L,240,98,...,8,36,44,23,12,10,11,22,-20.0,False
2297,22024,1610612748,MIA,Miami Heat,0022400147,2024-11-02,MIA @ WAS,W,240,118,...,21,44,65,19,6,3,13,18,20.0,False

There are five games that are included in the regular season, but not played in the home stadiums:
- 2025-01-25, IND against SAS, in Paris
- 2025-01-23, IND against SAS, in Paris
- 2024-12-14, HOU against OKC, in Las Vegas
- 2024-12-14, ATL against MIL, in Las Vegas
- 2024-11-02, MIA against WAS, in Mexico

In [85]:
df["GAME_ID"].nunique()

1230